"area:core":
  - 'source/**'
  - 'intern/**'
  - 'extern/**'

"area:ui":
  - 'source/blender/editors/interface/**'
  - 'release/datafiles/**'
  - 'scripts/startup/**'
  - 'scripts/addons_core/**'
  - 'scripts/addons_contrib/**'

"area:docs":
  - 'doc/**'
  - 'release/**/release_notes/**'

"area:build":
  - 'CMakeLists.txt'
  - 'build_files/**'
  - 'GNUmakefile'
  - 'make.bat'

"area:ci":
  - '.github/workflows/**'

"type:accessibility":
  - 'doc/**ui_accessibility*'
  - 'source/**/interface*'

"area:addons":
  - 'scripts/addons_*/*'

"area:extern":
  - 'extern/**'

"area:release":
  - 'release/**'
